name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NPM_GITHUB_TOKEN: ${{ secrets.RENOVATE_GITHUB_PACKAGE_TOKEN }}

    name: "Build"
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: "Prepare"
        run: |
          corepack enable

      - name: "Setup node"
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm lint
