name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NPM_GITHUB_TOKEN: ${{ secrets.RENOVATE_GITHUB_PACKAGE_TOKEN }}

    name: "Build"
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: "Setup node"
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm lint
