name: "renovate"

on:
  schedule:
    - cron: "0/30 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Renovate
        uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: ".github/renovate.config.cjs"
        env:
          LOG_LEVEL: "debug"
          RENOVATE_GITHUB_PACKAGE_TOKEN: ${{ secrets.RENOVATE_GITHUB_PACKAGE_TOKEN }}
