on:
  schedule:
    - cron: "0/30 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: ".github/renovate.json5"
        env:
          LOG_LEVEL: "debug"
